# Generated by Django 2.1.5 on 2019-01-17 18:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('mothers_name', models.CharField(max_length=150, null=True, verbose_name="Mother's Name")),
                ('fathers_name', models.CharField(max_length=150, null=True, verbose_name="Father's Name")),
                ('phones', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('addresses', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('documents', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('birthdate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
