# Generated by Django 2.1.5 on 2019-01-15 19:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('mothers_name', models.CharField(max_length=150, null=True, verbose_name="Mother's Name")),
                ('fathers_name', models.CharField(max_length=150, null=True, verbose_name="Father's Name")),
                ('phone', django.contrib.postgres.fields.jsonb.JSONField()),
                ('address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('document', django.contrib.postgres.fields.jsonb.JSONField()),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
