# Generated by Django 2.1.5 on 2019-01-17 19:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20190117_1848'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Product Item',
                'verbose_name_plural': 'Product Itens',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('O', 'Open'), ('W', 'Waiting Payment'), ('C', 'Canceled'), ('P', 'Payed')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_client', to='profiles.Profile')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_employe', to='profiles.Profile')),
                ('products', models.ManyToManyField(to='sales.ProductItem')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
