# Generated by Django 2.1.5 on 2019-01-17 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting Payment'), ('canceled', 'Canceled'), ('payed', 'Payed')], max_length=8),
        ),
    ]
