# Generated by Django 2.1.5 on 2019-01-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190117_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='product',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('waiting', 'Waiting Payment'), ('canceled', 'Canceled'), ('payed', 'Payed')], default='open', max_length=8),
        ),
    ]
