# Generated by Django 2.1.5 on 2019-01-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190121_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.AddField(
            model_name='productitem',
            name='sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.Sale'),
            preserve_default=False,
        ),
    ]
