# Generated by Django 2.1.5 on 2019-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
