# Generated by Django 2.1.5 on 2019-01-09 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Brazil', max_length=30, verbose_name='Country')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Neighborhood')),
                ('number', models.CharField(max_length=100, verbose_name='Number')),
                ('reference', models.TextField(max_length=100, verbose_name='Reference')),
                ('zipcode', models.CharField(max_length=8, verbose_name='Zip code')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, null=True, verbose_name='Nickname')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('addresses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=55)),
                ('ddd', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Phone'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
